apiVersion: v1
kind: ServiceAccount
metadata:
  name: iam-for-pods
  namespace: eks
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iam-for-pods
  namespace: eks
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - update
  - patch
  resourceNames:
  - "iam-for-pods"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iam-for-pods
  namespace: eks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iam-for-pods
subjects:
- kind: ServiceAccount
  name: iam-for-pods
  namespace: eks
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iam-for-pods
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iam-for-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iam-for-pods
subjects:
- kind: ServiceAccount
  name: iam-for-pods
  namespace: eks
